### PR TITLE
eval-free reconstructed types

### LINKED ISSUE #37: Tuple-of-type-of-closure cannot be reloaded
On 0.6,

```julia
julia> using FileIO, JLD2

julia> myfun() = x -> x
myfun (generic function with 1 method)

julia> save("test2.jld2", "groups", (typeof(myfun()),))

#### new session

julia> using FileIO, JLD2

julia> groups2 = load("test2.jld2", "groups")
Error encountered while loading "/Users/cedric/Programa/RL/notebooks/test2.jld2".
Fatal error:
ERROR: TypeError: read_data: in typeassert, expected DataType, got JLD2.UnknownType{String}
Stacktrace:
 [1] jlconvert at /Users/cedric/.julia/v0.6/JLD2/src/data.jl:1229 [inlined]
 [2] read_scalar at /Users/cedric/.julia/v0.6/JLD2/src/dataio.jl:37 [inlined]
 [3] read_data(::JLD2.JLDFile{JLD2.MmapIO}, ::JLD2.ReadRepresentation{Tuple{DataType},JLD2.OnDiskRepresentation{(0,),Tuple{DataType},Tuple{JLD2.OnDiskRepresentation{(0, 16),Tuple{String,Array{Any,1}},Tuple{JLD2.Vlen{String},JLD2.Vlen{JLD2.RelOffset}}}()}}()}, ::Array{JLD2.ReadAttribute,1}) at /Users/cedric/.julia/v0.6/JLD2/src/datasets.jl:171
 [4] read_data(::JLD2.JLDFile{JLD2.MmapIO}, ::JLD2.ReadDataspace, ::UInt8, ::Int64, ::Int64, ::Int64, ::UInt16, ::JLD2.RelOffset, ::Array{JLD2.ReadAttribute,1}) at /Users/cedric/.julia/v0.6/JLD2/src/datasets.jl:149
 [5] load_dataset(::JLD2.JLDFile{JLD2.MmapIO}, ::JLD2.RelOffset) at /Users/cedric/.julia/v0.6/JLD2/src/datasets.jl:92
 [6] getindex(::JLD2.Group{JLD2.JLDFile{JLD2.MmapIO}}, ::String) at /Users/cedric/.julia/v0.6/JLD2/src/groups.jl:108
 ```

EDIT: I expected to see `ReconstructedType`, instead of an error.

### LINKED ISSUE #298: DataType as tuple field
There seem to be bugs in the fallback reconstruction when fields of a `tuple` can not be reconstructed properly

```
julia> struct A; x::Int; end

julia> @save "test.jld2" b=(A(42),)

julia> 
 ~  julia                                                       29.6s  Wed 21 Apr 2021 01:11:59 PM CEST
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0 (2021-03-24)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using JLD2

julia> @load "test.jld2"
┌ Warning: type Main.A does not exist in workspace; reconstructing
└ @ JLD2 ~/.julia/packages/JLD2/qncOK/src/data/reconstructing_datatypes.jl:450
ERROR: TypeError: in <:, expected Type, got a value of type JLD2.OnDiskRepresentation{(0,), Tuple{Int64}, Tuple{Int64}}
Stacktrace:
  [1] constructrr(f::JLD2.JLDFile{JLD2.MmapIO}, T::DataType, dt::JLD2.CompoundDatatype, attrs::Vector{JLD2.ReadAttribute}, hard_failure::Bool)
    @ JLD2 ~/.julia/packages/JLD2/qncOK/src/data/reconstructing_datatypes.jl:183
  [2] constructrr(f::JLD2.JLDFile{JLD2.MmapIO}, T::DataType, dt::JLD2.CompoundDatatype, attrs::Vector{JLD2.ReadAttribute})
    @ JLD2 ~/.julia/packages/JLD2/qncOK/src/data/reconstructing_datatypes.jl:121
  [3] jltype(f::JLD2.JLDFile{JLD2.MmapIO}, cdt::JLD2.CommittedDatatype)
    @ JLD2 ~/.julia/packages/JLD2/qncOK/src/data/reconstructing_datatypes.jl:73
  [4] read_data(f::JLD2.JLDFile{JLD2.MmapIO}, dataspace::JLD2.ReadDataspace, datatype_class::UInt8, datatype_offset::Int64, data_offset::Int64, data_length::Int64, filter_id::UInt16, header_offset::JLD2.RelOffset, attributes::Vector{JLD2.ReadAttribute})
    @ JLD2 ~/.julia/packages/JLD2/qncOK/src/datasets.jl:146
  [5] load_dataset(f::JLD2.JLDFile{JLD2.MmapIO}, offset::JLD2.RelOffset)
    @ JLD2 ~/.julia/packages/JLD2/qncOK/src/datasets.jl:92
  [6] getindex(g::JLD2.Group{JLD2.JLDFile{JLD2.MmapIO}}, name::String)
    @ JLD2 ~/.julia/packages/JLD2/qncOK/src/groups.jl:108
  [7] read(f::JLD2.JLDFile{JLD2.MmapIO}, name::String)
    @ JLD2 ~/.julia/packages/JLD2/qncOK/src/JLD2.jl:346
  [8] #1
    @ ~/.julia/packages/JLD2/qncOK/src/loadsave.jl:145 [inlined]
  [9] jldopen(f::var"#1#2", args::String; kws::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ JLD2 ~/.julia/packages/JLD2/qncOK/src/loadsave.jl:4
 [10] jldopen(f::Function, args::String)
    @ JLD2 ~/.julia/packages/JLD2/qncOK/src/loadsave.jl:2
 [11] top-level scope
    @ ~/.julia/packages/JLD2/qncOK/src/loadsave.jl:144

```

### PR DESCRIPTION
**Pull request by JonasIsensee**
closes #298
closes #37

### CODE REVIEW

File: src/data/reconstructing_datatypes.jl [hunk 1]
```diff
@@ -425,39 +425,86 @@ constructrr(::JLDFile, ::Type{T}, dt::CompoundDatatype, ::Vector{ReadAttribute})
...
+# simple one-line display (without trailing line break)
+function Base.show(io::IO, f::ReconstructedStatic{N, FN, FT}) where {N,FN,FT}
+    print(io, "Reconstruct@$N($(values(getfield(f,1))))")
 end
 
+struct ReconstructedMutable{N, FN, FT} <: AbstractReconstructedType{N}
+    fields::Vector{Any}
+end
+
+function Base.getproperty(rc::ReconstructedMutable{N,FN,FT}, s::Symbol) where {N,FN,FT}
```
Comment (edls-group) [inline src/data/reconstructing_datatypes.jl:461]: you'll have to overwrite `propertynames` as well, else it defaults to using the field names (which are not accessible here)

**Review by edls-group — COMMENTED** [review]
seems to work for me
(also sorry I'm using the wrong account)
